Revert "try"
This reverts commit 7ba5a06efc591edee3733fa4bbb46e4e564238ed.

diff --git a/.github/workflows/python-cd.yml b/.github/workflows/python-cd.yml
--- a/.github/workflows/python-cd.yml
+++ b/.github/workflows/python-cd.yml
@@ -63,9 +63,22 @@ jobs:
         path: ./python/dist/*
 
   publish:
+    if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
     needs: build
     runs-on: ubuntu-latest
     steps:
+      - name: Validate tag
+        working-directory: ./python
+        shell: pwsh
+        run: |
+          $tag = "${{ github.ref }}".SubString(11)
+          $expectedFile = "dist/palletjack-$tag.tar.gz"
+
+          # Check whether the tag and the package version match together
+          if (-not (Test-Path -Path $expectedFile)) {
+              echo "::error ::Expected file $expectedFile doesn't exist"
+              exit 1
+          }
 
       - name: Download artifacts
         uses: actions/download-artifact@v4
@@ -73,7 +86,6 @@ jobs:
           pattern: dist-*
           path: dist
           merge-multiple: true
-
       - name: Display structure of downloaded files
         run: ls -R dist
 
