all-in

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -1,7 +1,7 @@
 # This workflow will install Python dependencies, run tests and lint with a single version of Python
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Python-ci
+name: Python-ci-cd-benchmarks
 
 on:
   push:
@@ -10,7 +10,7 @@ permissions:
   contents: read
 
 jobs:
-  pytest:
+  build:
     if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
 
     strategy:
@@ -108,16 +108,121 @@ jobs:
       env:
         VCPKG_TARGET_TRIPLET: ${{ steps.vcpkg-info.outputs.triplet }}
 
-#    - name: Build wheels
-#      working-directory: ./python
-#      run: python -m cibuildwheel --output-dir dist
-#      # to supply options, put them in 'env', like:
-#      env:
-#        CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --exclude libarrow.so.1500 --exclude libparquet.so.1500 -w {dest_dir} {wheel}
-#        CIBW_ENVIRONMENT: CYTHONIZE=1 VCPKG_TARGET_TRIPLET="${{ steps.vcpkg-info.outputs.triplet }}"
-#        CIBW_BUILD_VERBOSITY: 1
-#        # We use manylinux_2_28 for ABI compatibility with pyarrow
-#        # With the default image we were getting "undefined symbol: _ZNK5arrow6Status8ToStringEv" error (e.g https://github.com/ray-project/ray/issues/24566) 
-#        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28 
-#        # Disable unsupported builds
-#        CIBW_SKIP: "pp* *_i686 *-musllinux_* *win32"
+    - name: Build sdist (Linux)
+      if: runner.os == 'linux'
+      working-directory: ./python
+      run: |
+        python -m build --sdist         
+        
+   - name: Build wheels
+      working-directory: ./python
+      run: python -m cibuildwheel --output-dir dist
+      # to supply options, put them in 'env', like:
+      env:
+        CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair --exclude libarrow.so.1500 --exclude libparquet.so.1500 -w {dest_dir} {wheel}
+        CIBW_ENVIRONMENT: CYTHONIZE=1 VCPKG_TARGET_TRIPLET="${{ steps.vcpkg-info.outputs.triplet }}"
+        CIBW_BUILD_VERBOSITY: 1
+        # We use manylinux_2_28 for ABI compatibility with pyarrow
+        # With the default image we were getting "undefined symbol: _ZNK5arrow6Status8ToStringEv" error (e.g https://github.com/ray-project/ray/issues/24566) 
+        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28 
+        # Disable unsupported builds
+        CIBW_SKIP: "pp* *_i686 *-musllinux_* *win32"
+
+    - uses: actions/upload-artifact@v4
+      with:
+        name: dist-${{ matrix.os }}
+        path: ./python/dist/*
+
+  test:
+    needs: build
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+      fail-fast: false
+
+    runs-on: ${{ matrix.os }}
+    steps:
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v3
+      with:
+        python-version: "3.10"
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        pattern: dist-*
+        path: dist
+        merge-multiple: true
+          
+    - name: Test with pytest
+      working-directory: ./python
+      run: |
+        pip install --editable dist 
+        pytest
+
+  benchmarks:
+    needs: build
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+      fail-fast: false
+
+    runs-on: ${{ matrix.os }}
+    steps:
+    - uses: actions/checkout@v3
+    - name: Set up Python 3.10
+      uses: actions/setup-python@v3
+      with:
+        python-version: "3.10"
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        pattern: dist-*
+        path: dist
+        merge-multiple: true
+          
+    - name: Test with pytest
+      run: |
+        pip install dist 
+        pytest
+        
+    - name: Run benchmarks
+      run: |      
+        pip install dist
+        python3 ./benchmarks/benchmark_palletjack_metadata.py
+        
+  publish:
+    if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
+    needs: build,test,benchmarks
+    runs-on: ubuntu-latest
+    steps:
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v4
+      with:
+        pattern: dist-*
+        path: dist
+        merge-multiple: true
+    
+    - name: Display structure of downloaded files
+      run: ls -R dist
+    
+    - name: Validate tag
+      shell: pwsh
+      run: |
+        $tag = "${{ github.ref }}".SubString(11)
+        $expectedFile = "dist/palletjack-$tag.tar.gz"
+    
+        # Check whether the tag and the package version match together
+        if (-not (Test-Path -Path $expectedFile)) {
+            echo "::error ::Expected file $expectedFile doesn't exist"
+            exit 1
+        }
+    
+    - name: Publish to PyPi
+      uses: pypa/gh-action-pypi-publish@c12cc61414480c03e10ea76e2a0a1a17d6c764e2
+      with:
+        password: ${{ secrets.PYPI_API_TOKEN }}
+        packages-dir: dist	
+    
